### ISSUE TITLE
Howlerjs v 2.05 play after pause restarts the song from zero seconds

### ISSUE THREAD

**Issue by Stanley80** [goldfire/howlerjs.com#4]
Hello everybody,
thank you for your amazing work. 
I am implementing a plugin  in a social site with elgg engine.  I added a howlerjs sound player and everything worked fine, but If I start a song play pause when I push play again the song restarts from zero seconds instead of contuining from the seek position.

I don't kow if it can help, but if click on siriwave wave it it pauses my song insted of forwarding my track.

I spent many hours on that :(

Can You help me?

**Comment by goldfire** [comment]
Are you saying you based it off of the player example code? Does the player example on howlerjs.com work for you?

**Comment by Stanley80** [comment]
yes, I took the player example code. I modified the code to dinamically load songs of the user tracks. the code works if I run it from the howlerjs folder. in my site it loads the song and I listen the track correctly.But if I pause and restart a song it restarts from zero.

**Comment by Stanley80** [comment]
it does not return any error or warning in Chrome or Firefox console log

**Comment by Stanley80** [comment]
I found a problem at the line 760 of howler.core.js. It seems that in my plugin node.currentTime is set to zero even if seek is a float greater than zero.

I don't know how to solve the problem. 

Can you help me

Thank you very much
